"""adding price column

Revision ID: 046f359586e7
Revises: 7a468368e84a
Create Date: 2026-09-23 15:56:28.786889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046f359586e7'
down_revision: Union[str, Sequence[str], None] = '7a468368e84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('orders_list_items', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_list_items', 'price')
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###
