"""changin (name) to (username)

Revision ID: 386df9a754e3
Revises: 329b471488a7
Create Date: 2026-09-17 13:49:53.591922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386df9a754e3'
down_revision: Union[str, Sequence[str], None] = '329b471488a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=15), nullable=False))
    op.drop_constraint(op.f('users_name_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_name_key'), 'users', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
