"""adding nullable

Revision ID: 3962e57dbace
Revises: 0eaeb851c09f
Create Date: 2026-09-16 15:34:31.910574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3962e57dbace'
down_revision: Union[str, Sequence[str], None] = '0eaeb851c09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'is_took',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default="0")
    op.alter_column('orders', 'payed_to_taker',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default="0")
    op.alter_column('orders', 'received',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default="0")
    op.alter_column('orders', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default="0")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'done',
               existing_type=sa.BOOLEAN(),
               nullable=True,)
    op.alter_column('orders', 'received',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'payed_to_taker',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('orders', 'is_took',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
