"""empty message

Revision ID: 60d30549dba8
Revises: eb15ec63751d
Create Date: 2026-09-16 15:13:29.333682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d30549dba8'
down_revision: Union[str, Sequence[str], None] = 'eb15ec63751d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=200), server_default=sa.text('NULL'), nullable=True),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('is_took', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('taken_by_id', sa.Integer(), nullable=False),
    sa.Column('payed_to_taker', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('received', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('done', sa.Boolean(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
