"""adding orders list

Revision ID: 7a468368e84a
Revises: 97ba48c5d5f9
Create Date: 2026-09-23 15:50:37.177435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a468368e84a'
down_revision: Union[str, Sequence[str], None] = '97ba48c5d5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=25), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('applicant_name', sa.String(length=15), nullable=False),
    sa.Column('is_took', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('taken_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applicant_name'], ['users.username'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('order_name', sa.String(length=15), nullable=False),
    sa.Column('done', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['orders_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_list_items')
    op.drop_table('orders_list')
    # ### end Alembic commands ###
