"""adding applicant name

Revision ID: 97ba48c5d5f9
Revises: dbf4ce046566
Create Date: 2026-09-23 10:11:29.744380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ba48c5d5f9'
down_revision: Union[str, Sequence[str], None] = 'dbf4ce046566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('applicant_name', sa.String(length=15), nullable=False))
    op.create_foreign_key(None, 'orders', 'users', ['applicant_name'], ['username'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'applicant_name')
    # ### end Alembic commands ###
