"""adding total_price

Revision ID: daa7836f63c0
Revises: 603231a233df
Create Date: 2026-09-27 17:15:04.281434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa7836f63c0'
down_revision: Union[str, Sequence[str], None] = '603231a233df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_list', sa.Column('total_price', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders_list', 'total_price')
    # ### end Alembic commands ###
