"""fixing  nullable in taken_by_id

Revision ID: dbf4ce046566
Revises: 9c2525490c24
Create Date: 2026-09-21 13:51:50.725317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf4ce046566'
down_revision: Union[str, Sequence[str], None] = '9c2525490c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'taken_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'taken_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
